import type { ContentSection } from "@/types";
import { siteImageRef, siteImagePath, siteVideosAsMedia, HERO_BACKGROUND } from "@/lib/media/site-assets";

/** Approved core message — grammar polished, meaning unchanged. */
export const CORE_MESSAGE =
  "Light for Immigrants is a not-for-profit organization in Ontario, Canada dedicated to supporting immigrants and Canadian communities and promoting equity through programs, services, and advocacy. Our mission is to bring light, guidance, and practical support to immigrants and help create a community where everyone belongs, regardless of background. By working together, we develop innovative solutions to challenges and create a better future for every immigrant in Canada. Join the Light for Immigrants family today.";

export const CORE_VALUES = [
  {
    key: "inclusivity",
    title: "Inclusivity",
    description:
      "We welcome people of every background, language, and life stage with dignity and respect.",
  },
  {
    key: "collaboration",
    title: "Collaboration",
    description:
      "We build bridges between newcomers, neighbours, and partner organizations across Ontario.",
  },
  {
    key: "empowerment",
    title: "Empowerment",
    description:
      "We equip immigrants with practical tools, confidence, and connections to move forward.",
  },
  {
    key: "advocacy",
    title: "Advocacy",
    description:
      "We amplify immigrant voices and work toward fair, equitable policies and practices.",
  },
  {
    key: "service",
    title: "Service",
    description:
      "We show up with compassion, responsiveness, and a commitment to community wellbeing.",
  },
  {
    key: "integrity",
    title: "Integrity",
    description:
      "We are transparent, accountable, and honest in how we support the people we serve.",
  },
] as const;

export type PageSeedDefinition = {
  slug: string;
  title: string;
  status: "draft" | "published" | "archived";
  hero: {
    eyebrow?: string;
    heading?: string;
    subheading?: string;
    bodyHtml?: string;
    backgroundImage?: string;
    backgroundImageAlt?: string;
    mobileBackgroundImage?: string;
    theme?: string;
  };
  sections: ContentSection[];
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    socialImage?: string;
    noIndex?: boolean;
  };
};

function img(n: number, alt: string) {
  return siteImageRef(n, alt);
}

function valuesGridHtml() {
  return `<ul>${CORE_VALUES.map(
    (v) => `<li><strong>${v.title}</strong> — ${v.description}</li>`,
  ).join("")}</ul>`;
}

export const PAGE_DEFINITIONS: PageSeedDefinition[] = [
  {
    slug: "home",
    title: "Home",
    status: "published",
    hero: {
      eyebrow: "Ontario, Canada • Supporting every new beginning",
      heading: "A brighter beginning starts here.",
      subheading:
        "Guidance, community and practical support for immigrants building a new life in Canada.",
      bodyHtml: `<p>${CORE_MESSAGE}</p>`,
      backgroundImage: "/images/hero-background.png",
      backgroundImageAlt: "Community looking toward the Toronto skyline at sunset",
      theme: "dark",
    },
    sections: [
      {
        key: "trust-strip",
        type: "trust-strip",
        internalLabel: "Trust strip",
        eyebrow: "Community-led support",
        heading: "Rooted in Ontario, open to all",
        bodyHtml:
          "<p>Programs shaped with immigrants, families, youth, seniors, volunteers, and partner organizations.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "who-we-are",
        type: "split-editorial",
        internalLabel: "Who we are",
        eyebrow: "Who we are",
        heading: "A beacon for newcomers and neighbours alike",
        bodyHtml: `<p>${CORE_MESSAGE}</p>`,
        media: [img(2, "Community members connecting at a welcome event")],
        primaryCta: { label: "About us", href: "/about" },
        secondaryCta: { label: "Our programs", href: "/services" },
        layout: "split-left",
        theme: "ivory",
        isVisible: true,
        order: 1,
        animation: "from-left",
      },
      {
        key: "core-values",
        type: "values-grid",
        internalLabel: "Core values",
        eyebrow: "What guides us",
        heading: "Values that shape every program",
        bodyHtml: valuesGridHtml(),
        media: [
          img(3, "Hands joined in solidarity"),
          img(4, "Workshop participants learning together"),
        ],
        isVisible: true,
        order: 2,
        animation: "stagger",
      },
      {
        key: "featured-services",
        type: "services-preview",
        internalLabel: "Featured services",
        eyebrow: "Programs & services",
        heading: "Support tailored to your journey",
        subheading: "Explore settlement, language, employment, wellbeing, and more.",
        primaryCta: { label: "View all services", href: "/services" },
        secondaryCta: { label: "Book support", href: "/booking" },
        layout: "card-grid",
        isVisible: true,
        order: 3,
        animation: "from-right",
      },
      {
        key: "impact-metrics",
        type: "metrics",
        internalLabel: "Impact metrics",
        eyebrow: "Community impact",
        heading: "Growing together — placeholder figures",
        bodyHtml:
          "<p><em>Editable seed placeholders until verified numbers are supplied by the organization.</em></p><ul><li><strong>500+</strong> orientation conversations</li><li><strong>120+</strong> workshops delivered</li><li><strong>40+</strong> community partners</li><li><strong>15</strong> languages supported in referrals</li></ul>",
        media: [img(5, "Community celebration with diverse families")],
        isVisible: true,
        order: 4,
        animation: "fade",
      },
      {
        key: "journey",
        type: "sticky-journey",
        internalLabel: "Immigrant journey",
        eyebrow: "From arrival to belonging",
        heading: "Welcome. Navigate. Connect. Grow. Lead.",
        bodyHtml:
          "<ol><li><strong>Welcome</strong> — Orientation and first connections.</li><li><strong>Navigate</strong> — Practical guidance for daily life in Canada.</li><li><strong>Connect</strong> — Programs that build friendships and networks.</li><li><strong>Grow</strong> — Skills, employment, and confidence-building.</li><li><strong>Lead</strong> — Mentorship, advocacy, and community leadership.</li></ol>",
        media: [
          img(1, "Newcomer receiving a warm welcome"),
          img(2, "Youth mentorship session"),
          img(3, "Senior community gathering"),
        ],
        layout: "scrollytelling",
        theme: "dark",
        isVisible: true,
        order: 5,
        animation: "mask-reveal",
      },
      {
        key: "gallery-preview",
        type: "gallery-mosaic",
        internalLabel: "Gallery preview",
        eyebrow: "Community moments",
        heading: "See the light in action",
        primaryCta: { label: "View gallery", href: "/gallery" },
        media: [
          img(4, "Community event highlight"),
          img(5, "Volunteers at a welcome day"),
          img(1, "Workshop participants"),
        ],
        isVisible: true,
        order: 6,
        animation: "stagger",
      },
      {
        key: "community-videos",
        type: "video-showcase",
        internalLabel: "Community videos",
        eyebrow: "See us in action",
        heading: "Moments from our community",
        subheading: "Highlights from welcome days, workshops, and gatherings across Ontario.",
        media: siteVideosAsMedia(),
        theme: "ivory",
        isVisible: true,
        order: 7,
        animation: "fade",
      },
      {
        key: "testimonials-preview",
        type: "testimonials-carousel",
        internalLabel: "Testimonials preview",
        eyebrow: "Voices from the community",
        heading: "Stories of connection and growth",
        secondaryCta: { label: "Read more stories", href: "/testimonials" },
        isVisible: true,
        order: 8,
        animation: "fade",
      },
      {
        key: "news-preview",
        type: "blog-preview",
        internalLabel: "Latest news",
        eyebrow: "News & insights",
        heading: "Updates from Light for Immigrants",
        primaryCta: { label: "Read the blog", href: "/blog" },
        isVisible: false,
        order: 8,
        animation: "from-bottom",
      },
      {
        key: "get-support-cta",
        type: "cta-band",
        internalLabel: "Get support CTA",
        eyebrow: "We are here for you",
        heading: "Ready to take the next step?",
        subheading: "Reach out for guidance, programs, or volunteer opportunities.",
        bodyHtml:
          "<p>Our team connects you with practical support — not legal advice. For immigration legal matters, we can help you find appropriate referrals.</p>",
        primaryCta: { label: "Get support", href: "/contact" },
        secondaryCta: { label: "Get involved", href: "/get-involved" },
        media: [img(2, "Community members walking together")],
        theme: "red",
        isVisible: true,
        order: 9,
        animation: "from-top",
      },
    ],
    seo: {
      metaTitle: "Light for Immigrants | Arrive. Belong. Thrive.",
      metaDescription: CORE_MESSAGE.slice(0, 155),
      socialImage: HERO_BACKGROUND,
    },
  },
  {
    slug: "about",
    title: "About",
    status: "published",
    hero: {
      eyebrow: "Our story",
      heading: "Light for every immigrant journey",
      subheading: "Guidance, belonging, and practical support across Ontario.",
      backgroundImage: siteImagePath(5),
      backgroundImageAlt: "Diverse group in collaborative discussion",
      theme: "dark",
    },
    sections: [
      {
        key: "organization-story",
        type: "split-editorial",
        internalLabel: "Organization story",
        eyebrow: "Who we are",
        heading: "Built with immigrants, for immigrants",
        bodyHtml: `<p>${CORE_MESSAGE}</p>`,
        media: [img(1, "Community orientation session")],
        isVisible: true,
        order: 0,
        animation: "from-left",
      },
      {
        key: "mission-vision",
        type: "mission-vision",
        internalLabel: "Mission & vision",
        eyebrow: "Purpose",
        heading: "Our mission",
        subheading: "Bringing light, guidance, and belonging to every newcomer in Ontario.",
        bodyHtml: `<p>Light for Immigrants is a not-for-profit organization dedicated to supporting immigrants and Canadian communities through practical programs, compassionate service, and community-led advocacy.</p><p>Our mission is to bring light, guidance, and practical support to immigrants — helping families navigate settlement, build confidence, access resources, and feel genuinely welcomed in their new home.</p><p>We believe everyone deserves dignity, connection, and a fair chance to thrive. By working together with neighbours, volunteers, and partner organizations, we create pathways from arrival to belonging.</p>`,
        media: [img(15, "Community workshop and learning together")],
        layout: "split-left",
        isVisible: true,
        order: 1,
        animation: "fade",
      },
      {
        key: "our-vision",
        type: "split-editorial",
        internalLabel: "Our vision",
        eyebrow: "Where we are headed",
        heading: "Our vision",
        subheading: "A future where every newcomer can thrive with dignity and belonging.",
        bodyHtml:
          "<p>A Canada where every immigrant is welcomed, supported, and empowered to contribute fully to community life.</p><p>We envision neighbourhoods where newcomers are not outsiders, but neighbours — connected through language programs, mentorship, cultural celebrations, and pathways to employment and leadership.</p><p>Through advocacy and partnership, we work toward fair systems and shared prosperity for all who call Canada home.</p>",
        media: [img(25, "Volunteers welcoming newcomers")],
        theme: "dark",
        layout: "split-left",
        isVisible: true,
        order: 2,
        animation: "from-right",
      },
      {
        key: "core-values",
        type: "values-grid",
        internalLabel: "Core values",
        eyebrow: "Our values",
        heading: "What we stand for",
        bodyHtml: valuesGridHtml(),
        media: [img(4, "Volunteers collaborating"), img(5, "Community workshop")],
        isVisible: true,
        order: 3,
        animation: "stagger",
      },
      {
        key: "foundation-promise",
        type: "rich-text",
        internalLabel: "Foundation promise",
        eyebrow: "Our promise",
        heading: "Compassionate support without promises we cannot keep",
        bodyHtml:
          "<p>We provide information, referrals, and community programs. We do not provide immigration legal advice, guarantee outcomes, or represent ourselves as licensed consultants or a law firm.</p>",
        isVisible: true,
        order: 4,
        animation: "from-right",
      },
      {
        key: "advocacy-approach",
        type: "split-editorial",
        internalLabel: "Advocacy approach",
        eyebrow: "Advocacy",
        heading: "Equity through collective action",
        bodyHtml:
          "<p>We partner with communities and organizations to address barriers, amplify immigrant voices, and promote fair access to services and opportunities across Ontario.</p>",
        media: [img(2, "Community advocacy gathering")],
        primaryCta: {
          label: "Learn about advocacy programs",
          href: "/services/advocacy-equity-civic-engagement",
        },
        isVisible: true,
        order: 5,
        animation: "from-left",
      },
      {
        key: "milestones",
        type: "timeline",
        internalLabel: "Milestones",
        eyebrow: "Our journey",
        heading: "Milestones to be updated",
        bodyHtml:
          "<p><em>Add verified milestones through the admin panel when ready.</em></p><ul><li>Community programs launched across the GTA</li><li>Partnerships with local service providers</li><li>Volunteer and mentorship networks expanded</li></ul>",
        isVisible: true,
        order: 6,
        animation: "fade",
      },
      {
        key: "impact",
        type: "metrics",
        internalLabel: "Impact section",
        eyebrow: "Impact",
        heading: "Impact that grows with community input",
        bodyHtml:
          "<p>Impact numbers are editable placeholders until the organization supplies verified data.</p>",
        media: [img(1, "Families at a community event")],
        isVisible: true,
        order: 7,
        animation: "stagger",
      },
      {
        key: "team-preview",
        type: "team-preview",
        internalLabel: "Team preview",
        eyebrow: "Our people",
        heading: "Meet the team behind the mission",
        primaryCta: { label: "View full team", href: "/team" },
        isVisible: true,
        order: 8,
        animation: "from-bottom",
      },
      {
        key: "partners-collage",
        type: "media-collage",
        internalLabel: "Partners collage",
        eyebrow: "Community partners",
        heading: "Stronger together",
        bodyHtml:
          "<p>We collaborate with schools, faith communities, settlement agencies, and local businesses — partner names can be added in admin.</p>",
        media: [
          img(3, "Partnership handshake"),
          img(4, "Community coalition meeting"),
          img(5, "Volunteer team photo"),
        ],
        isVisible: true,
        order: 9,
        animation: "mask-reveal",
      },
      {
        key: "about-cta",
        type: "cta-band",
        internalLabel: "About CTA",
        heading: "Join the Light for Immigrants family",
        primaryCta: { label: "Get involved", href: "/get-involved" },
        secondaryCta: { label: "Contact us", href: "/contact" },
        theme: "red",
        isVisible: true,
        order: 10,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "About | Light for Immigrants",
      metaDescription:
        "Learn about Light for Immigrants — an Ontario not-for-profit bringing light, guidance, and belonging to immigrants and Canadian communities.",
    },
  },
  {
    slug: "services",
    title: "Services",
    status: "published",
    hero: {
      eyebrow: "Programs & services",
      heading: "Support for every stage of your journey",
      subheading: "Settlement, language, employment, wellbeing, and community connection.",
      theme: "dark",
    },
    sections: [
      {
        key: "intro",
        type: "rich-text",
        internalLabel: "Intro copy",
        heading: "Programs shaped around real needs",
        bodyHtml:
          "<p>Our services are designed with input from immigrants, families, and partner organizations. Browse by category or search for a program that fits your goals.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "category-filters",
        type: "service-filters",
        internalLabel: "Category filters",
        heading: "Find the right support",
        bodyHtml: "<p>Filter by category to explore programs.</p>",
        isVisible: true,
        order: 1,
        animation: "from-top",
      },
      {
        key: "services-grid",
        type: "services-grid",
        internalLabel: "Services grid",
        heading: "Our programs",
        subheading: "Each service links to a detailed page with eligibility, process, and next steps.",
        isVisible: true,
        order: 2,
        animation: "stagger",
      },
      {
        key: "how-support-works",
        type: "process-steps",
        internalLabel: "How support works",
        eyebrow: "How it works",
        heading: "Four steps to getting support",
        bodyHtml:
          "<ol><li><strong>Reach out</strong> — Contact us or submit a booking request.</li><li><strong>Connect</strong> — We learn about your goals and circumstances.</li><li><strong>Plan</strong> — Together we identify programs, referrals, or next steps.</li><li><strong>Follow through</strong> — We stay connected and adjust support as needed.</li></ol>",
        media: [img(1, "Staff member welcoming a newcomer")],
        isVisible: true,
        order: 3,
        animation: "from-left",
      },
      {
        key: "services-media-band",
        type: "media-band",
        internalLabel: "Media band",
        heading: "Community-led, culturally responsive",
        media: [
          img(2, "Language support session"),
          img(3, "Employment readiness workshop"),
          img(4, "Youth mentorship program"),
        ],
        isVisible: true,
        order: 4,
        animation: "mask-reveal",
      },
      {
        key: "services-cta",
        type: "cta-band",
        internalLabel: "Services CTA",
        heading: "Not sure where to start?",
        subheading: "We will help you find the right program or referral.",
        primaryCta: { label: "Book a conversation", href: "/booking" },
        secondaryCta: { label: "Contact us", href: "/contact" },
        theme: "red",
        isVisible: true,
        order: 5,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Services | Light for Immigrants",
      metaDescription:
        "Explore settlement, language, employment, youth, family, seniors, mental health referrals, recreation, education, and advocacy programs.",
    },
  },
  {
    slug: "gallery",
    title: "Gallery",
    status: "published",
    hero: {
      eyebrow: "Community gallery",
      heading: "Moments of connection and celebration",
      subheading: "Events, workshops, welcome days, and partnerships across Ontario.",
      backgroundImage: siteImagePath(12),
      backgroundImageAlt: "Collage of community event moments",
      theme: "dark",
    },
    sections: [
      {
        key: "gallery-intro",
        type: "rich-text",
        internalLabel: "Gallery intro",
        bodyHtml:
          "<p>Browse photos and videos from programs, events, and volunteer initiatives. Media is managed in the admin gallery module.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "gallery-filters",
        type: "gallery-filters",
        internalLabel: "Category filters",
        heading: "Explore by category",
        isVisible: true,
        order: 1,
        animation: "from-top",
      },
      {
        key: "gallery-grid",
        type: "gallery-masonry",
        internalLabel: "Gallery grid",
        heading: "Community in focus",
        isVisible: true,
        order: 2,
        animation: "stagger",
      },
      {
        key: "gallery-story",
        type: "split-editorial",
        internalLabel: "Gallery story",
        eyebrow: "Behind the lens",
        heading: "Every image tells a story of belonging",
        bodyHtml:
          "<p>From welcome days to youth workshops, our gallery reflects the diversity and resilience of the communities we serve.</p>",
        media: [img(5, "Community celebration")],
        isVisible: true,
        order: 3,
        animation: "from-left",
      },
      {
        key: "gallery-volunteer-cta",
        type: "cta-band",
        internalLabel: "Gallery CTA",
        heading: "Want to share your community story?",
        primaryCta: { label: "Get involved", href: "/get-involved" },
        secondaryCta: { label: "Contact us", href: "/contact" },
        isVisible: true,
        order: 4,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Gallery | Light for Immigrants",
      metaDescription: "Photos and videos from Light for Immigrants community programs and events.",
    },
  },
  {
    slug: "testimonials",
    title: "Testimonials",
    status: "published",
    hero: {
      eyebrow: "Community voices",
      heading: "Stories of arrival, resilience, and belonging",
      backgroundImage: siteImagePath(20),
      backgroundImageAlt: "Community members sharing stories",
      theme: "dark",
    },
    sections: [
      {
        key: "testimonials-intro",
        type: "rich-text",
        internalLabel: "Testimonials intro",
        bodyHtml:
          "<p>These stories come from newcomers, families, youth, seniors, and volunteers who have walked alongside Light for Immigrants in Ontario. Each voice reflects a real journey toward confidence, connection, and belonging.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "testimonials-slider",
        type: "testimonials-slider",
        internalLabel: "Main slider",
        heading: "What community members share",
        isVisible: true,
        order: 1,
        animation: "stagger",
      },
      {
        key: "community-stories",
        type: "story-grid",
        internalLabel: "Community stories",
        eyebrow: "Community stories",
        heading: "Paths to confidence and connection",
        media: [
          img(10, "Community member sharing their story"),
          img(14, "Youth mentorship moment"),
          img(18, "Family at a community event"),
        ],
        isVisible: true,
        order: 2,
        animation: "from-right",
      },
      {
        key: "share-story",
        type: "split-editorial",
        internalLabel: "Share your story",
        heading: "Share your experience",
        bodyHtml:
          "<p>If Light for Immigrants has supported your journey, we welcome your story — with your consent and approval before anything is published.</p>",
        primaryCta: { label: "Contact us", href: "/contact" },
        isVisible: true,
        order: 3,
        animation: "from-left",
      },
      {
        key: "testimonials-cta",
        type: "cta-band",
        internalLabel: "Testimonials CTA",
        heading: "Ready to write your next chapter?",
        primaryCta: { label: "Explore programs", href: "/services" },
        secondaryCta: { label: "Get support", href: "/booking" },
        theme: "red",
        isVisible: true,
        order: 4,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Testimonials | Light for Immigrants",
      metaDescription: "Community stories and testimonials from Light for Immigrants programs.",
    },
  },
  {
    slug: "faqs",
    title: "FAQs",
    status: "published",
    hero: {
      eyebrow: "Help centre",
      heading: "Answers to common questions",
      subheading: "Services, eligibility, appointments, volunteering, and more.",
      backgroundImage: siteImagePath(14),
      backgroundImageAlt: "Community members seeking information",
      theme: "dark",
    },
    sections: [
      {
        key: "faq-search",
        type: "faq-search",
        internalLabel: "FAQ search",
        heading: "Search questions",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "faq-accordion",
        type: "faq-accordion",
        internalLabel: "FAQ accordion",
        heading: "Frequently asked questions",
        isVisible: true,
        order: 1,
        animation: "stagger",
      },
      {
        key: "faq-photo-strip",
        type: "media-collage",
        internalLabel: "Community photo strip",
        eyebrow: "Community",
        heading: "We are here to help",
        media: [
          img(2, "Information session"),
          img(3, "Volunteer helping newcomer"),
          img(4, "Workshop Q&A"),
          img(5, "Community desk"),
          img(1, "Friendly staff greeting"),
        ],
        layout: "ribbon",
        isVisible: true,
        order: 2,
        animation: "mask-reveal",
      },
      {
        key: "faq-limitations",
        type: "rich-text",
        internalLabel: "Limitations notice",
        heading: "Important to know",
        bodyHtml:
          "<p>Information on this site is for general guidance. It does not replace legal advice, licensed immigration consulting, or emergency services. In an emergency, call 911.</p>",
        isVisible: true,
        order: 3,
        animation: "fade",
      },
      {
        key: "faq-cta",
        type: "cta-band",
        internalLabel: "Still need help CTA",
        heading: "Still need help?",
        subheading: "Our team can point you to the right program or referral.",
        primaryCta: { label: "Contact us", href: "/contact" },
        secondaryCta: { label: "Book a request", href: "/booking" },
        theme: "red",
        isVisible: true,
        order: 4,
        animation: "from-bottom",
      },
    ],
    seo: {
      metaTitle: "FAQs | Light for Immigrants",
      metaDescription:
        "Frequently asked questions about Light for Immigrants programs, eligibility, and support.",
    },
  },
  {
    slug: "contact",
    title: "Contact",
    status: "published",
    hero: {
      eyebrow: "Get in touch",
      heading: "We would love to hear from you",
      subheading: "Questions, program inquiries, partnerships, and volunteer interest welcome.",
      backgroundImage: siteImagePath(5),
      backgroundImageAlt: "Contact and community welcome desk",
      theme: "dark",
    },
    sections: [
      {
        key: "contact-cards",
        type: "contact-cards",
        internalLabel: "Contact cards",
        heading: "Reach our team",
        bodyHtml:
          "<p>Contact details are loaded from Site Settings and update automatically across the site.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "contact-form",
        type: "contact-form",
        internalLabel: "Contact form",
        heading: "Send a message",
        bodyHtml:
          "<p>Include as much detail as you can. We aim to respond within two business days.</p>",
        isVisible: true,
        order: 1,
        animation: "from-left",
      },
      {
        key: "contact-photo-strip",
        type: "media-collage",
        internalLabel: "Photo strip",
        media: [
          img(3, "Office welcome area"),
          img(4, "Community phone support"),
          img(5, "Map and directions"),
          img(1, "Team at reception"),
          img(2, "Multilingual resources"),
        ],
        layout: "ribbon",
        isVisible: true,
        order: 2,
        animation: "stagger",
      },
      {
        key: "contact-hours",
        type: "rich-text",
        internalLabel: "Office hours",
        eyebrow: "Hours",
        heading: "When we are available",
        bodyHtml:
          "<p>Monday – Friday: 9:00 AM – 5:00 PM (editable in Settings). For urgent mental health or safety concerns, contact appropriate emergency or crisis services.</p>",
        isVisible: true,
        order: 3,
        animation: "fade",
      },
      {
        key: "contact-map",
        type: "map-embed",
        internalLabel: "Map",
        heading: "Visit us in Toronto",
        bodyHtml: "<p>163 Queen St E, Toronto — map link configured in Site Settings.</p>",
        isVisible: true,
        order: 4,
        animation: "from-right",
      },
    ],
    seo: {
      metaTitle: "Contact | Light for Immigrants",
      metaDescription:
        "Contact Light for Immigrants for program information, partnerships, and volunteer opportunities.",
    },
  },
  {
    slug: "blog",
    title: "Blog",
    status: "published",
    hero: {
      eyebrow: "News & insights",
      heading: "Stories, updates, and community news",
      backgroundImage: siteImagePath(8),
      backgroundImageAlt: "Editorial community news imagery",
      theme: "dark",
    },
    sections: [
      {
        key: "blog-featured",
        type: "blog-featured",
        internalLabel: "Featured story",
        heading: "Featured article",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "blog-filters",
        type: "blog-filters",
        internalLabel: "Categories & search",
        heading: "Browse articles",
        isVisible: true,
        order: 1,
        animation: "from-top",
      },
      {
        key: "blog-grid",
        type: "blog-grid",
        internalLabel: "Article grid",
        heading: "Latest from Light for Immigrants",
        isVisible: true,
        order: 2,
        animation: "stagger",
      },
      {
        key: "blog-newsletter",
        type: "split-editorial",
        internalLabel: "Stay connected",
        heading: "Stay connected with our community",
        bodyHtml:
          "<p>Follow our blog for program updates, event recaps, and resources for newcomers.</p>",
        media: [img(4, "Reading community newsletter")],
        primaryCta: { label: "Contact us to subscribe", href: "/contact" },
        isVisible: true,
        order: 3,
        animation: "from-left",
      },
      {
        key: "blog-cta",
        type: "cta-band",
        internalLabel: "Blog CTA",
        heading: "Have a story idea?",
        primaryCta: { label: "Get in touch", href: "/contact" },
        isVisible: true,
        order: 4,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Blog | Light for Immigrants",
      metaDescription: "News, updates, and community stories from Light for Immigrants.",
    },
  },
  {
    slug: "booking",
    title: "Booking",
    status: "published",
    hero: {
      eyebrow: "Request support",
      heading: "Book a conversation",
      subheading: "Submit a request — our team will follow up to confirm next steps.",
      backgroundImage: siteImagePath(12),
      backgroundImageAlt: "Scheduling a support conversation",
      theme: "dark",
    },
    sections: [
      {
        key: "booking-intro",
        type: "rich-text",
        internalLabel: "Booking intro",
        bodyHtml:
          "<p>This is a request form, not a guaranteed appointment calendar. We will contact you to schedule a suitable time.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "booking-steps",
        type: "process-steps",
        internalLabel: "Booking steps",
        eyebrow: "What to expect",
        heading: "Simple steps to connect",
        bodyHtml:
          "<ol><li>Complete the form with your contact details and preferred times.</li><li>Select a service or describe your needs.</li><li>Our team reviews your request and responds by email or phone.</li><li>We confirm timing and any documents to bring.</li></ol>",
        media: [img(1, "Booking consultation")],
        isVisible: true,
        order: 1,
        animation: "from-left",
      },
      {
        key: "booking-form",
        type: "booking-form",
        internalLabel: "Booking form",
        heading: "Request form",
        isVisible: true,
        order: 2,
        animation: "from-right",
      },
      {
        key: "booking-faq-link",
        type: "rich-text",
        internalLabel: "Booking FAQ link",
        heading: "Questions before booking?",
        bodyHtml:
          '<p>Visit our <a href="/faqs">FAQs</a> or <a href="/contact">contact page</a> for general inquiries.</p>',
        isVisible: true,
        order: 3,
        animation: "fade",
      },
      {
        key: "booking-media",
        type: "media-band",
        internalLabel: "Booking media",
        media: [
          img(2, "Support session"),
          img(3, "Community desk"),
          img(5, "Welcome conversation"),
        ],
        isVisible: true,
        order: 4,
        animation: "stagger",
      },
    ],
    seo: {
      metaTitle: "Booking | Light for Immigrants",
      metaDescription: "Request a conversation or program intake with Light for Immigrants.",
    },
  },
  {
    slug: "team",
    title: "Team",
    status: "published",
    hero: {
      eyebrow: "Our team",
      heading: "People who bring the mission to life",
      subheading: "Leadership, program staff, and volunteers — profiles managed in admin.",
      backgroundImage: siteImagePath(20),
      backgroundImageAlt: "Team members collaborating",
      theme: "dark",
    },
    sections: [
      {
        key: "team-intro",
        type: "rich-text",
        internalLabel: "Team intro",
        bodyHtml:
          "<p>Team profiles are published when photos and bios are approved. Placeholder entries remain in draft until real information is supplied.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "leadership-grid",
        type: "team-grid",
        internalLabel: "Leadership grid",
        eyebrow: "Leadership",
        heading: "Leadership team",
        layout: "leadership",
        isVisible: true,
        order: 1,
        animation: "stagger",
      },
      {
        key: "team-grid",
        type: "team-grid",
        internalLabel: "Full team grid",
        heading: "Program and community team",
        isVisible: true,
        order: 2,
        animation: "from-bottom",
      },
      {
        key: "team-values",
        type: "values-grid",
        internalLabel: "Team values",
        heading: "How we work together",
        bodyHtml: valuesGridHtml(),
        media: [img(1, "Team meeting"), img(2, "Volunteer coordination")],
        isVisible: true,
        order: 3,
        animation: "from-left",
      },
      {
        key: "team-cta",
        type: "cta-band",
        internalLabel: "Join team CTA",
        heading: "Interested in joining our team or volunteering?",
        primaryCta: { label: "Get involved", href: "/get-involved" },
        secondaryCta: { label: "Contact us", href: "/contact" },
        theme: "red",
        isVisible: true,
        order: 4,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Team | Light for Immigrants",
      metaDescription: "Meet the Light for Immigrants team and leadership.",
    },
  },
  {
    slug: "shop",
    title: "Shop",
    status: "published",
    hero: {
      eyebrow: "Community shop",
      heading: "Resources and merchandise",
      subheading: "A catalog for future community products — inquire before ordering.",
      backgroundImage: siteImagePath(14),
      backgroundImageAlt: "Community shop products display",
      theme: "dark",
    },
    sections: [
      {
        key: "shop-intro",
        type: "rich-text",
        internalLabel: "Shop intro",
        bodyHtml:
          "<p>Browse community resources and merchandise. Payment processing is not enabled — use the contact flow to ask about availability.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "shop-grid",
        type: "product-grid",
        internalLabel: "Product grid",
        heading: "Available items",
        isVisible: true,
        order: 1,
        animation: "stagger",
      },
      {
        key: "shop-story",
        type: "split-editorial",
        internalLabel: "Shop story",
        heading: "Every purchase supports community programs",
        bodyHtml:
          "<p>Revenue from select items helps fund workshops, welcome kits, and youth initiatives. Details available on request.</p>",
        media: [img(3, "Community merchandise")],
        isVisible: true,
        order: 2,
        animation: "from-left",
      },
      {
        key: "shop-media",
        type: "media-band",
        internalLabel: "Shop media",
        media: [img(4, "Resource materials"), img(5, "Community tote bags")],
        isVisible: true,
        order: 3,
        animation: "mask-reveal",
      },
      {
        key: "shop-cta",
        type: "cta-band",
        internalLabel: "Shop CTA",
        heading: "Ask about an item",
        primaryCta: { label: "Contact us", href: "/contact" },
        secondaryCta: { label: "View programs", href: "/services" },
        isVisible: true,
        order: 4,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Shop | Light for Immigrants",
      metaDescription: "Community resources and merchandise from Light for Immigrants.",
    },
  },
  {
    slug: "pricing",
    title: "Pricing",
    status: "published",
    hero: {
      eyebrow: "Programs & partnerships",
      heading: "Tailored support — contact us for details",
      subheading: "No fixed packages. Every partnership and program is shaped around community needs.",
      backgroundImage: siteImagePath(5),
      backgroundImageAlt: "Discussion about tailored community programs",
      theme: "dark",
    },
    sections: [
      {
        key: "pricing-intro",
        type: "rich-text",
        internalLabel: "Pricing intro",
        bodyHtml:
          "<p>Light for Immigrants does not publish invented dollar amounts. Community programs, workshops, and partnerships are customized — reach out to discuss scope and funding.</p>",
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "pricing-cards",
        type: "pricing-cards",
        internalLabel: "Pricing cards",
        heading: "How we work with you",
        isVisible: true,
        order: 1,
        animation: "stagger",
      },
      {
        key: "pricing-process",
        type: "process-steps",
        internalLabel: "Partnership process",
        eyebrow: "Partnerships",
        heading: "From first conversation to program design",
        bodyHtml:
          "<ol><li>Share your goals and community context.</li><li>We outline possible formats and referrals.</li><li>Together we agree on scope, timing, and resources.</li><li>Programs launch with ongoing feedback and adjustment.</li></ol>",
        media: [img(3, "Partnership planning session")],
        isVisible: true,
        order: 2,
        animation: "from-left",
      },
      {
        key: "pricing-faq",
        type: "rich-text",
        internalLabel: "Pricing FAQ",
        heading: "Common questions",
        bodyHtml:
          "<p>Many core programs are offered at no cost to participants thanks to grants and donations. Partner-funded workshops and events are quoted based on scope.</p>",
        isVisible: true,
        order: 3,
        animation: "fade",
      },
      {
        key: "pricing-cta",
        type: "cta-band",
        internalLabel: "Pricing CTA",
        heading: "Let's design something together",
        primaryCta: { label: "Contact us", href: "/contact" },
        secondaryCta: { label: "Get involved", href: "/get-involved" },
        theme: "red",
        isVisible: true,
        order: 4,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Pricing | Light for Immigrants",
      metaDescription:
        "Light for Immigrants offers tailored community programs and partnerships — contact us for details.",
    },
  },
  {
    slug: "get-involved",
    title: "Get Involved",
    status: "published",
    hero: {
      eyebrow: "Join us",
      heading: "Volunteer, partner, mentor, or sponsor",
      subheading: "There is a place for you in the Light for Immigrants family.",
      backgroundImage: siteImagePath(8),
      backgroundImageAlt: "Volunteers and community partners",
      theme: "dark",
    },
    sections: [
      {
        key: "involve-intro",
        type: "rich-text",
        internalLabel: "Get involved intro",
        bodyHtml: `<p>${CORE_MESSAGE}</p>`,
        isVisible: true,
        order: 0,
        animation: "fade",
      },
      {
        key: "volunteer-path",
        type: "path-cards",
        internalLabel: "Volunteer path",
        eyebrow: "Volunteer",
        heading: "Share your time and talents",
        bodyHtml:
          "<p>Support welcome days, workshops, translation, mentoring, and event logistics.</p>",
        media: [img(1, "Volunteers at event")],
        primaryCta: { label: "Volunteer interest", href: "/contact" },
        isVisible: true,
        order: 1,
        animation: "from-left",
      },
      {
        key: "partner-path",
        type: "path-cards",
        internalLabel: "Partner path",
        eyebrow: "Partner",
        heading: "Organizations and businesses",
        bodyHtml:
          "<p>Co-design programs, sponsor events, or provide in-kind resources for newcomers.</p>",
        media: [img(2, "Partnership meeting")],
        primaryCta: { label: "Partnership inquiry", href: "/contact" },
        isVisible: true,
        order: 2,
        animation: "from-right",
      },
      {
        key: "mentor-path",
        type: "path-cards",
        internalLabel: "Mentor path",
        eyebrow: "Mentor",
        heading: "Guide the next generation",
        bodyHtml:
          "<p>Youth mentorship and career conversations make a lasting difference.</p>",
        media: [img(4, "Mentor and youth")],
        isVisible: true,
        order: 3,
        animation: "stagger",
      },
      {
        key: "sponsor-path",
        type: "path-cards",
        internalLabel: "Sponsor path",
        eyebrow: "Sponsor",
        heading: "Fund community impact",
        bodyHtml:
          "<p>Sponsors help expand workshops, welcome kits, and recreation programs.</p>",
        primaryCta: { label: "Donate", href: "/donate" },
        isVisible: true,
        order: 4,
        animation: "fade",
      },
      {
        key: "involve-cta",
        type: "cta-band",
        internalLabel: "Get involved CTA",
        heading: "Ready to join the Light for Immigrants family?",
        primaryCta: { label: "Contact us", href: "/contact" },
        secondaryCta: { label: "View programs", href: "/services" },
        theme: "red",
        isVisible: true,
        order: 5,
        animation: "from-bottom",
      },
    ],
    seo: {
      metaTitle: "Get Involved | Light for Immigrants",
      metaDescription: "Volunteer, partner, mentor, or sponsor with Light for Immigrants in Ontario.",
    },
  },
  {
    slug: "donate",
    title: "Donate",
    status: "published",
    hero: {
      eyebrow: "Support the mission",
      heading: "Help us bring light to more immigrants",
      subheading: "Your generosity fuels programs, workshops, and community connection.",
      backgroundImage: siteImagePath(12),
      backgroundImageAlt: "Community supported by generous donors",
      theme: "dark",
    },
    sections: [
      {
        key: "donate-mission",
        type: "split-editorial",
        internalLabel: "Donation mission",
        heading: "Why your support matters",
        bodyHtml: `<p>${CORE_MESSAGE}</p>`,
        media: [img(5, "Community gratitude moment")],
        isVisible: true,
        order: 0,
        animation: "from-left",
      },
      {
        key: "donate-impact",
        type: "metrics",
        internalLabel: "Donation impact",
        heading: "Where contributions go",
        bodyHtml:
          "<ul><li>Welcome and orientation resources for newcomers</li><li>Youth mentorship and recreation programs</li><li>Workshops on language, employment, and wellbeing</li><li>Community events that build belonging</li></ul>",
        isVisible: true,
        order: 1,
        animation: "stagger",
      },
      {
        key: "donate-methods",
        type: "rich-text",
        internalLabel: "Donation methods",
        heading: "How to give",
        bodyHtml:
          "<p>Online donation link is configured in Site Settings. Card processing is enabled only when a payment provider is supplied. You may also contact us about in-kind gifts and corporate sponsorship.</p>",
        isVisible: true,
        order: 2,
        animation: "fade",
      },
      {
        key: "donate-transparency",
        type: "rich-text",
        internalLabel: "Transparency",
        heading: "Transparency and accountability",
        bodyHtml:
          "<p>We do not make unsupported legal claims about charitable registration. Financial and impact reporting can be shared as the organization publishes official materials.</p>",
        isVisible: true,
        order: 3,
        animation: "from-right",
      },
      {
        key: "donate-cta",
        type: "cta-band",
        internalLabel: "Donate CTA",
        heading: "Every gift expands belonging",
        primaryCta: { label: "Contact us to donate", href: "/contact" },
        secondaryCta: { label: "Get involved", href: "/get-involved" },
        theme: "red",
        isVisible: true,
        order: 4,
        animation: "fade",
      },
    ],
    seo: {
      metaTitle: "Donate | Light for Immigrants",
      metaDescription: "Support Light for Immigrants programs and community initiatives in Ontario.",
    },
  },
  {
    slug: "privacy",
    title: "Privacy Policy",
    status: "published",
    hero: {
      eyebrow: "Legal",
      heading: "Privacy Policy",
      subheading: "How we collect, use, and protect your information.",
      theme: "light",
    },
    sections: [
      {
        key: "privacy-intro",
        type: "legal-content",
        internalLabel: "Privacy intro",
        bodyHtml:
          "<p>Light for Immigrants respects your privacy. This policy describes how we handle personal information submitted through our website, forms, and programs.</p>",
        isVisible: true,
        order: 0,
        animation: "none",
      },
      {
        key: "privacy-collection",
        type: "legal-content",
        internalLabel: "Information we collect",
        heading: "Information we collect",
        bodyHtml:
          "<p>We may collect name, contact details, program interests, and messages you submit voluntarily. Technical data such as browser type may be collected in server logs for security.</p>",
        isVisible: true,
        order: 1,
        animation: "none",
      },
      {
        key: "privacy-use",
        type: "legal-content",
        internalLabel: "How we use information",
        heading: "How we use your information",
        bodyHtml:
          "<p>Information is used to respond to inquiries, coordinate programs, improve services, and meet legal obligations. We do not sell personal information.</p>",
        isVisible: true,
        order: 2,
        animation: "none",
      },
      {
        key: "privacy-rights",
        type: "legal-content",
        internalLabel: "Your rights",
        heading: "Your rights",
        bodyHtml:
          "<p>You may request access, correction, or deletion of your personal information where applicable under Canadian privacy law. Contact us using the details in Site Settings.</p>",
        isVisible: true,
        order: 3,
        animation: "none",
      },
      {
        key: "privacy-contact",
        type: "legal-content",
        internalLabel: "Privacy contact",
        heading: "Contact",
        bodyHtml:
          "<p>For privacy questions, reach out through our contact page. Contact email and address are managed in Site Settings.</p>",
        isVisible: true,
        order: 4,
        animation: "none",
      },
    ],
    seo: {
      metaTitle: "Privacy Policy | Light for Immigrants",
      metaDescription: "Privacy policy for Light for Immigrants website and programs.",
      noIndex: false,
    },
  },
  {
    slug: "terms",
    title: "Terms of Use",
    status: "published",
    hero: {
      eyebrow: "Legal",
      heading: "Terms of Use",
      subheading: "Conditions for using this website and its content.",
      theme: "light",
    },
    sections: [
      {
        key: "terms-intro",
        type: "legal-content",
        internalLabel: "Terms intro",
        bodyHtml:
          "<p>By using this website, you agree to these terms. If you do not agree, please discontinue use.</p>",
        isVisible: true,
        order: 0,
        animation: "none",
      },
      {
        key: "terms-content",
        type: "legal-content",
        internalLabel: "Website content",
        heading: "Website content",
        bodyHtml:
          "<p>Content is provided for general information about Light for Immigrants programs. It may be updated without notice.</p>",
        isVisible: true,
        order: 1,
        animation: "none",
      },
      {
        key: "terms-no-advice",
        type: "legal-content",
        internalLabel: "No legal advice",
        heading: "No legal or immigration advice",
        bodyHtml:
          "<p>Information on this site does not constitute legal advice, immigration consulting, or guaranteed outcomes. Consult licensed professionals for legal matters.</p>",
        isVisible: true,
        order: 2,
        animation: "none",
      },
      {
        key: "terms-liability",
        type: "legal-content",
        internalLabel: "Limitation of liability",
        heading: "Limitation of liability",
        bodyHtml:
          "<p>Light for Immigrants is not liable for damages arising from use of this website, except where prohibited by applicable law.</p>",
        isVisible: true,
        order: 3,
        animation: "none",
      },
      {
        key: "terms-contact",
        type: "legal-content",
        internalLabel: "Terms contact",
        heading: "Contact",
        bodyHtml: "<p>Questions about these terms may be directed through our contact page.</p>",
        isVisible: true,
        order: 4,
        animation: "none",
      },
    ],
    seo: {
      metaTitle: "Terms of Use | Light for Immigrants",
      metaDescription: "Terms of use for the Light for Immigrants website.",
    },
  },
];
